const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  authGetSession: () => ipcRenderer.invoke('auth-get-session'),
  authLogin: (payload) => ipcRenderer.invoke('auth-login', payload),
  authLogout: () => ipcRenderer.invoke('auth-logout'),
  authGetProfile: () => ipcRenderer.invoke('auth-get-profile'),
  authUpdateSettings: (payload) => ipcRenderer.invoke('auth-update-settings', payload),
  authChangePassword: (payload) => ipcRenderer.invoke('auth-change-password', payload),
  authUpdateProfile: (payload) => ipcRenderer.invoke('auth-update-profile', payload),
  authUploadAvatar: (payload) => ipcRenderer.invoke('auth-upload-avatar', payload),
  updaterCheckNow: () => ipcRenderer.invoke('updater-check-now'),
  updaterInstallNow: () => ipcRenderer.invoke('updater-install-now'),
  getAppVersion: () => ipcRenderer.invoke('app-get-version'),
  getStatus: () => ipcRenderer.invoke('get-status'),
  getActions: () => ipcRenderer.invoke('get-actions'),
  getActionMeta: () => ipcRenderer.invoke('get-action-meta'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  saveHotkey: (hotkey) => ipcRenderer.invoke('save-hotkey', hotkey),
  deleteHotkey: (id) => ipcRenderer.invoke('delete-hotkey', id),
  checkConflict: (keys, excludeId) => ipcRenderer.invoke('check-conflict', { keys, excludeId }),
  formatKeys: (keys) => ipcRenderer.invoke('format-keys', keys),
  startRecording: () => ipcRenderer.invoke('start-recording'),
  stopRecording: () => ipcRenderer.invoke('stop-recording'),
  testAction: (action) => ipcRenderer.invoke('test-action', action),
  toggleServer: (run) => ipcRenderer.invoke('toggle-server', run),
  connectFigma: () => ipcRenderer.invoke('connect-figma'),
  setTheme: (theme) => ipcRenderer.invoke('set-theme', theme),
  setCdpPort: (port) => ipcRenderer.invoke('set-cdp-port', port),
  openConfigFolder: () => ipcRenderer.invoke('open-config-folder'),
  openPluginFolder: () => ipcRenderer.invoke('open-plugin-folder'),
  openKeyboardMapper: () => ipcRenderer.invoke('open-keyboard-mapper'),
  sendMakePrompt: (prompt) => ipcRenderer.invoke('figma-make-send', prompt),
  speechSupported: () => ipcRenderer.invoke('speech-supported'),
  speechListLanguages: () => ipcRenderer.invoke('speech-list-languages'),
  speechStart: (lang) => ipcRenderer.invoke('speech-start', { lang }),
  speechStop: () => ipcRenderer.invoke('speech-stop'),
  onSpeechInterim: (cb) => ipcRenderer.on('speech-interim', (_e, d) => cb(d)),
  onSpeechResult: (cb) => ipcRenderer.on('speech-result', (_e, d) => cb(d)),
  onSpeechError: (cb) => ipcRenderer.on('speech-error', (_e, d) => cb(d)),
  getTemplates: () => ipcRenderer.invoke('get-templates'),
  copyTemplate: (templateId) => ipcRenderer.invoke('copy-template', templateId),
  getUserTemplateThumb: (templateId, options) => ipcRenderer.invoke('get-user-template-thumb', templateId, options),
  updateUserTemplate: (id, patch) => ipcRenderer.invoke('update-user-template', { id, patch }),
  deleteUserTemplate: (id) => ipcRenderer.invoke('delete-user-template', id),
  metaskSync: () => ipcRenderer.invoke('metask-sync'),
  metaskConsumePendingUpdates: () => ipcRenderer.invoke('metask-consume-pending-updates'),
  metaskConsumePendingCommentUpdates: () => ipcRenderer.invoke('metask-consume-pending-comment-updates'),
  metaskAttachBoard: () => ipcRenderer.invoke('metask-attach-board'),
  metaskDetachBoard: () => ipcRenderer.invoke('metask-detach-board'),
  metaskResizeBoard: () => ipcRenderer.invoke('metask-resize-board'),
  metaskOpenIssue: (url) => ipcRenderer.invoke('metask-open-issue', url),
  metaskGetInfo: () => ipcRenderer.invoke('metask-get-info'),
  metaskSaveCredentials: (creds) => ipcRenderer.invoke('metask-save-credentials', creds),
  metaskGetLoginScript: (creds) => ipcRenderer.invoke('metask-get-login-script', creds),
  metaskClearSession: () => ipcRenderer.invoke('metask-clear-session'),
  metaskReloadBoard: () => ipcRenderer.invoke('metask-reload-board'),
  metaskOpenExternal: (url) => ipcRenderer.invoke('metask-open-external', url),
  metaskAddComment: (payload) => ipcRenderer.invoke('metask-add-comment', payload),
  metaskAddLaborLog: (payload) => ipcRenderer.invoke('metask-add-labor-log', payload),
  mailGetInfo: () => ipcRenderer.invoke('mail-get-info'),
  mailGetLoginScript: (creds) => ipcRenderer.invoke('mail-get-login-script', creds),
  mailClearSession: () => ipcRenderer.invoke('mail-clear-session'),
  mailSaveCredentials: (creds) => ipcRenderer.invoke('mail-save-credentials', creds),
  mailOpenExternal: (url) => ipcRenderer.invoke('mail-open-external', url),
  webtabOpenExternal: (url) => ipcRenderer.invoke('webtab-open-external', url),
  webtabClearSession: (partition) => ipcRenderer.invoke('webtab-clear-session', partition),
  agentGetStatus: () => ipcRenderer.invoke('agent-get-status'),
  agentSendMessage: (payload) => ipcRenderer.invoke('agent-send-message', payload),
  agentPickImage: () => ipcRenderer.invoke('agent-pick-image'),
  agentTestConnection: () => ipcRenderer.invoke('agent-test-connection'),
  agentSaveCredentials: (creds) => ipcRenderer.invoke('agent-save-credentials', creds),
  agentOpenGigaChatDocs: () => ipcRenderer.invoke('agent-open-gigachat-docs'),
  agentGetMorningBrief: () => ipcRenderer.invoke('agent-get-morning-brief'),
  agentBannerToNanobanana: (payload) => ipcRenderer.invoke('agent-banner-to-nanobanana', payload),
  agentFigmaPlan: (payload) => ipcRenderer.invoke('agent-figma-plan', payload),
  agentFigmaApply: (payload) => ipcRenderer.invoke('agent-figma-apply', payload),
  agentSiteBuild: (payload) => ipcRenderer.invoke('agent-site-build', payload),
  agentMobbinStatus: () => ipcRenderer.invoke('agent-mobbin-status'),
  designMemoryList: () => ipcRenderer.invoke('design-memory-list'),
  designMemoryAdd: (payload) => ipcRenderer.invoke('design-memory-add', payload),
  designMemorySync: (payload) => ipcRenderer.invoke('design-memory-sync', payload),
  magnificStatus: () => ipcRenderer.invoke('magnific-status'),
  magnificConnect: (payload) => ipcRenderer.invoke('magnific-connect', payload),
  magnificDisconnect: () => ipcRenderer.invoke('magnific-disconnect'),
  magnificGetTools: () => ipcRenderer.invoke('magnific-get-tools'),
  magnificCallTool: (payload) => ipcRenderer.invoke('magnific-call-tool', payload),
  magnificPickReferenceImages: () => ipcRenderer.invoke('magnific-pick-reference-images'),
  agentFindTaskLinks: (payload) => ipcRenderer.invoke('agent-find-task-links', payload),
  agentLinkTasks: (payload) => ipcRenderer.invoke('agent-link-tasks', payload),
  agentDismissTaskLink: (payload) => ipcRenderer.invoke('agent-dismiss-task-link', payload),
  agentPostMockupsToTask: (payload) => ipcRenderer.invoke('agent-post-mockups-to-task', payload),
  agentNotifyBackground: (payload) => ipcRenderer.invoke('agent-notify-background', payload),
  nanobananaGetModels: () => ipcRenderer.invoke('nanobanana-get-models'),
  nanobananaGetCredits: () => ipcRenderer.invoke('nanobanana-get-credits'),
  nanobananaGenerate: (payload) => ipcRenderer.invoke('nanobanana-generate', payload),
  nanobananaGetGallery: () => ipcRenderer.invoke('nanobanana-get-gallery'),
  nanobananaDeleteGalleryItem: (id) => ipcRenderer.invoke('nanobanana-delete-gallery-item', id),
  nanobananaClearGallery: () => ipcRenderer.invoke('nanobanana-clear-gallery'),
  nanobananaSaveCredentials: (creds) => ipcRenderer.invoke('nanobanana-save-credentials', creds),
  nanobananaOpenDocs: () => ipcRenderer.invoke('nanobanana-open-docs'),
  nanobananaDownloadImage: (payload) => ipcRenderer.invoke('nanobanana-download-image', payload),
  nanobananaResolveImageDataUrl: (payload) => ipcRenderer.invoke('nanobanana-resolve-image-data-url', payload),
  nanobananaPickReferenceImages: () => ipcRenderer.invoke('nanobanana-pick-reference-images'),
  bannerMockupGetPresets: () => ipcRenderer.invoke('banner-mockup-get-presets'),
  bannerMockupApply: (payload) => ipcRenderer.invoke('banner-mockup-apply', payload),
  bannerMockupReadFigmaTexts: (templateId) => ipcRenderer.invoke('banner-mockup-read-figma-texts', { templateId }),
  getNotesLibrary: () => ipcRenderer.invoke('notes-get-library'),
  saveBookmark: (data) => ipcRenderer.invoke('notes-save-bookmark', data),
  deleteBookmark: (id) => ipcRenderer.invoke('notes-delete-bookmark', id),
  saveNote: (data) => ipcRenderer.invoke('notes-save-note', data),
  deleteNote: (id) => ipcRenderer.invoke('notes-delete-note', id),
  notesOpenUrl: (url) => ipcRenderer.invoke('notes-open-url', url),
  completeOnboarding: () => ipcRenderer.invoke('complete-onboarding'),
  updateAppSettings: (updates) => ipcRenderer.invoke('update-app-settings', updates),
  resetAppSettings: () => ipcRenderer.invoke('reset-app-settings'),
  resetOnboarding: () => ipcRenderer.invoke('reset-onboarding'),
  resizeWindow: (width, height) => ipcRenderer.invoke('resize-window', { width, height }),
  exportConfig: () => ipcRenderer.invoke('export-config'),
  importConfig: () => ipcRenderer.invoke('import-config'),
  saveCustomTheme: (theme) => ipcRenderer.invoke('custom-theme-save', theme),
  deleteCustomTheme: (themeId) => ipcRenderer.invoke('custom-theme-delete', themeId),
  pickCustomThemeMedia: (themeId, role) => ipcRenderer.invoke('custom-theme-pick-media', { themeId, role }),
  getCustomThemeMediaUrl: (themeId, filename) => ipcRenderer.invoke('custom-theme-media-url', { themeId, filename }),
  onStatus: (cb) => ipcRenderer.on('status', (_e, d) => cb(d)),
  onLog: (cb) => ipcRenderer.on('log', (_e, d) => cb(d)),
  onConfig: (cb) => ipcRenderer.on('config', (_e, d) => cb(d)),
  onAuthChanged: (cb) => ipcRenderer.on('auth-changed', (_e, d) => cb(d)),
  onUpdaterStatus: (cb) => ipcRenderer.on('updater-status', (_e, d) => cb(d)),
  onActionFired: (cb) => ipcRenderer.on('action-fired', (_e, d) => cb(d)),
  onLibraryUpdated: (cb) => ipcRenderer.on('library-updated', (_e, d) => cb(d)),
  onMetaskSessionReady: (cb) => ipcRenderer.on('metask-session-ready', (_e, d) => cb(d)),
  onMetaskWindowResized: (cb) => ipcRenderer.on('metask-window-resized', (_e, d) => cb(d)),
  onMetaskTasksUpdated: (cb) => ipcRenderer.on('metask-tasks-updated', (_e, d) => cb(d)),
  onMetaskTaskUpdates: (cb) => ipcRenderer.on('metask-task-updates', (_e, d) => cb(d)),
  onMetaskCommentUpdates: (cb) => ipcRenderer.on('metask-comment-updates', (_e, d) => cb(d)),
  onMetaskOpenTask: (cb) => ipcRenderer.on('metask-open-task', (_e, d) => cb(d)),
  onMetaskIssueActive: (cb) => ipcRenderer.on('metask-issue-active', (_e, d) => cb(d)),
  onNotesUpdated: (cb) => ipcRenderer.on('notes-updated', (_e, d) => cb(d)),
});
